name: open_mail_app
description: This library provides the ability to query the device for installed email apps and open those apps
version: 0.4.0
homepage: https://github.com/HomeXLabs/open-mail-app-flutter

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.12.0"

dependencies:
  platform: ^3.0.2
  url_launcher: ^6.0.2
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.homex.open_mail_app
        pluginClass: OpenMailAppPlugin
      ios:
        pluginClass: OpenMailAppPlugin
