name: open_mail_app
description: This library provides the ability to query the device for installed email apps and open those apps
version: 0.0.5
homepage: https://github.com/HomeXLabs/open-mail-app-flutter

environment:
  sdk: ">=2.3.0 <3.0.0"
  flutter: ">=1.12.0 <2.0.0"

dependencies:
  url_launcher: ^5.5.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.homex.open_mail_app
        pluginClass: OpenMailAppPlugin
      ios:
        pluginClass: OpenMailAppPlugin